import React, { useState, useMemo } from "react";
import { MindMapData, MindMapNode, SubjectType } from "../types";
import { PREBUILT_MIND_MAPS } from "../data/mindMapData";
import { 
  GitBranch, 
  Workflow, 
  Sparkles, 
  Lightbulb, 
  AlertTriangle, 
  BookOpen, 
  Search, 
  ChevronRight, 
  ChevronDown, 
  Copy, 
  Check, 
  Maximize2, 
  Minimize2, 
  Filter, 
  Compass, 
  Bookmark, 
  ArrowRight,
  Send,
  Loader2,
  Layers,
  FileText
} from "lucide-react";

interface MindMapsViewProps {
  onAskAIAboutTopic?: (topicTitle: string) => void;
  onNavigateToNotes?: (topicId?: string) => void;
}

export const MindMapsView: React.FC<MindMapsViewProps> = ({
  onAskAIAboutTopic,
  onNavigateToNotes,
}) => {
  const [mindMaps, setMindMaps] = useState<MindMapData[]>(PREBUILT_MIND_MAPS);
  const [selectedMindMapId, setSelectedMindMapId] = useState<string>(PREBUILT_MIND_MAPS[0].id);
  const [viewMode, setViewMode] = useState<"tree" | "flowchart" | "shortcuts">("tree");
  const [selectedSubject, setSelectedSubject] = useState<string>("All");
  const [selectedExamFilter, setSelectedExamFilter] = useState<string>("All");
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [activeNodeDetails, setActiveNodeDetails] = useState<MindMapNode | null>(null);
  const [collapsedNodeIds, setCollapsedNodeIds] = useState<Set<string>>(new Set());
  const [copiedMnemonic, setCopiedMnemonic] = useState<boolean>(false);
  const [isAiGenerating, setIsAiGenerating] = useState<boolean>(false);
  const [aiTopicInput, setAiTopicInput] = useState<string>("");
  const [aiError, setAiError] = useState<string | null>(null);

  // Active Mind Map
  const activeMap = useMemo(() => {
    return mindMaps.find((m) => m.id === selectedMindMapId) || mindMaps[0];
  }, [mindMaps, selectedMindMapId]);

  // Filtered List of Mind Maps
  const filteredMindMaps = useMemo(() => {
    return mindMaps.filter((m) => {
      const matchSubject = selectedSubject === "All" || m.subject === selectedSubject;
      const matchExam = selectedExamFilter === "All" || m.examFocus.includes(selectedExamFilter as any);
      const matchSearch = 
        !searchQuery.trim() || 
        m.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
        m.description.toLowerCase().includes(searchQuery.toLowerCase());
      return matchSubject && matchExam && matchSearch;
    });
  }, [mindMaps, selectedSubject, selectedExamFilter, searchQuery]);

  // Toggle node expansion
  const toggleNode = (nodeId: string) => {
    setCollapsedNodeIds((prev) => {
      const next = new Set(prev);
      if (next.has(nodeId)) {
        next.delete(nodeId);
      } else {
        next.add(nodeId);
      }
      return next;
    });
  };

  // Expand all / collapse all
  const expandAll = () => setCollapsedNodeIds(new Set());
  const collapseAll = () => {
    const allIds = new Set<string>();
    const collect = (node: MindMapNode) => {
      if (node.children && node.children.length > 0) {
        allIds.add(node.id);
        node.children.forEach(collect);
      }
    };
    if (activeMap) {
      collect(activeMap.rootNode);
    }
    setCollapsedNodeIds(allIds);
  };

  // AI Generator Handler
  const handleGenerateAiMindMap = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiTopicInput.trim() || isAiGenerating) return;

    setIsAiGenerating(true);
    setAiError(null);

    try {
      const response = await fetch("/api/ai/generate-mindmap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: aiTopicInput.trim(),
          subject: selectedSubject !== "All" ? selectedSubject : "Polity",
          examFocus: selectedExamFilter !== "All" ? selectedExamFilter : "Both UPSC & UPPSC",
        }),
      });

      if (!response.ok) {
        throw new Error("Server failed to generate mind map. Please check your API key.");
      }

      const data = await response.json();
      if (data.mindMap && data.mindMap.rootNode) {
        const newMap: MindMapData = {
          id: `ai-${Date.now()}`,
          title: data.mindMap.title || aiTopicInput.trim(),
          subject: (data.mindMap.subject as SubjectType) || "Polity",
          description: data.mindMap.description || `AI Synthesized Mind Map & Flowchart for ${aiTopicInput}`,
          examFocus: ["UPSC Prelims", "UPSC Mains", "UPPSC Prelims", "UPPSC Mains"],
          sources: data.mindMap.sources || ["NCERTs & Standard References"],
          shortcutMnemonic: data.mindMap.shortcutMnemonic || "Key concept generated by MyndMap AI",
          flowchart: data.mindMap.flowchart,
          rootNode: data.mindMap.rootNode,
        };

        setMindMaps((prev) => [newMap, ...prev]);
        setSelectedMindMapId(newMap.id);
        setAiTopicInput("");
      } else {
        throw new Error("Invalid format returned by AI.");
      }
    } catch (err: any) {
      setAiError(err.message || "Failed to generate AI mind map.");
    } finally {
      setIsAiGenerating(false);
    }
  };

  const copyMnemonicText = () => {
    if (activeMap?.shortcutMnemonic) {
      navigator.clipboard.writeText(activeMap.shortcutMnemonic);
      setCopiedMnemonic(true);
      setTimeout(() => setCopiedMnemonic(false), 2000);
    }
  };

  // Recursive Tree Node Renderer
  const renderTreeNode = (node: MindMapNode, depth: number = 0) => {
    const hasChildren = node.children && node.children.length > 0;
    const isCollapsed = collapsedNodeIds.has(node.id);
    const isSelected = activeNodeDetails?.id === node.id;

    // Badge styling based on node type
    const getNodeBadgeStyle = () => {
      switch (node.type) {
        case "root":
          return "bg-slate-900 text-amber-300 border-slate-800 shadow-md font-bold text-base";
        case "category":
          return "bg-amber-50 text-amber-950 border-amber-300 font-semibold text-sm";
        case "trap":
          return "bg-rose-50 text-rose-950 border-rose-300 font-medium text-xs";
        case "mains_keyword":
          return "bg-violet-50 text-violet-950 border-violet-300 font-medium text-xs";
        case "exam_fact":
          return "bg-emerald-50 text-emerald-950 border-emerald-300 font-medium text-xs";
        default:
          return "bg-white text-slate-800 border-slate-200 font-medium text-xs";
      }
    };

    return (
      <div key={node.id} className="relative my-2 pl-4 sm:pl-6 border-l-2 border-slate-200">
        <div className="flex items-start gap-2">
          {hasChildren && (
            <button
              onClick={() => toggleNode(node.id)}
              className="mt-1 w-5 h-5 rounded-sm bg-slate-100 hover:bg-slate-200 text-slate-600 flex items-center justify-center transition-colors shrink-0"
              title={isCollapsed ? "Expand node" : "Collapse node"}
            >
              {isCollapsed ? <ChevronRight size={14} /> : <ChevronDown size={14} />}
            </button>
          )}

          <div
            onClick={() => setActiveNodeDetails(node)}
            className={`cursor-pointer px-3 py-2 rounded-lg border transition-all duration-150 flex-1 max-w-xl ${getNodeBadgeStyle()} ${
              isSelected ? "ring-2 ring-amber-500 shadow-sm" : "hover:border-amber-400"
            }`}
          >
            <div className="flex items-center justify-between gap-2">
              <span className="leading-snug">{node.label}</span>
              {node.type === "trap" && (
                <span className="px-1.5 py-0.5 rounded text-[10px] bg-rose-200/60 text-rose-800 font-bold shrink-0">
                  ⚠️ Trap
                </span>
              )}
              {node.type === "mains_keyword" && (
                <span className="px-1.5 py-0.5 rounded text-[10px] bg-violet-200/60 text-violet-800 font-bold shrink-0">
                  ✍️ Mains
                </span>
              )}
              {node.type === "exam_fact" && (
                <span className="px-1.5 py-0.5 rounded text-[10px] bg-emerald-200/60 text-emerald-800 font-bold shrink-0">
                  🎯 Prelims
                </span>
              )}
            </div>

            {node.notes && (
              <p className="text-[11px] mt-1 text-slate-600 font-normal leading-relaxed line-clamp-2">
                {node.notes}
              </p>
            )}
          </div>
        </div>

        {/* Recursive Children */}
        {hasChildren && !isCollapsed && (
          <div className="mt-1">
            {node.children!.map((child) => renderTreeNode(child, depth + 1))}
          </div>
        )}
      </div>
    );
  };

  const subjectsList: ("All" | SubjectType)[] = [
    "All",
    "Polity",
    "Economy",
    "Geography",
    "Environment",
    "History & Culture",
    "UP Special",
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6">
      
      {/* Top Banner & AI Generator */}
      <div className="bg-white rounded-xl p-5 sm:p-6 border border-slate-200/80 shadow-xs space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="p-1.5 rounded-lg bg-amber-100 text-amber-800">
                <GitBranch size={20} />
              </span>
              <h2 className="text-xl sm:text-2xl font-bold font-display text-slate-900">
                Visual Concept Mind Maps & Flowcharts
              </h2>
            </div>
            <p className="text-sm text-slate-600 mt-1">
              Multi-source synthesis from NCERTs, Laxmikanth, Shankar IAS & UP GS 5/6. Designed for rapid cognitive recall, Prelims traps & Mains answer enrichment.
            </p>
          </div>

          {/* Mode Switcher */}
          <div className="flex items-center gap-1 bg-slate-100 p-1 rounded-lg self-start shrink-0 border border-slate-200">
            <button
              onClick={() => setViewMode("tree")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                viewMode === "tree"
                  ? "bg-white text-slate-900 shadow-xs"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              <Layers size={14} />
              Concept Tree
            </button>
            <button
              onClick={() => setViewMode("flowchart")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                viewMode === "flowchart"
                  ? "bg-white text-slate-900 shadow-xs"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              <Workflow size={14} />
              Flowchart Mode
            </button>
            <button
              onClick={() => setViewMode("shortcuts")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                viewMode === "shortcuts"
                  ? "bg-white text-slate-900 shadow-xs"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              <Lightbulb size={14} />
              Mnemonics & Shortcuts
            </button>
          </div>
        </div>

        {/* AI Mind Map Generator Bar */}
        <form onSubmit={handleGenerateAiMindMap} className="pt-3 border-t border-slate-100">
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
            <div className="relative flex-1">
              <Sparkles size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-amber-600" />
              <input
                type="text"
                value={aiTopicInput}
                onChange={(e) => setAiTopicInput(e.target.value)}
                placeholder="Generate custom Mind Map & Flowchart with AI (e.g. 73rd Amendment, Monsoon Walker Cell, UP Ken-Betwa Link)..."
                className="w-full pl-9 pr-4 py-2 text-xs sm:text-sm rounded-lg border border-amber-200/80 bg-amber-50/30 focus:bg-white focus:outline-none focus:ring-2 focus:ring-amber-500 transition-all text-slate-900 placeholder:text-slate-400"
              />
            </div>
            <button
              type="submit"
              disabled={isAiGenerating || !aiTopicInput.trim()}
              className="flex items-center justify-center gap-1.5 px-4 py-2 rounded-lg bg-amber-800 hover:bg-amber-900 text-amber-50 text-xs sm:text-sm font-semibold transition-all disabled:opacity-50 shrink-0 shadow-xs"
            >
              {isAiGenerating ? (
                <>
                  <Loader2 size={16} className="animate-spin" />
                  Generating Map...
                </>
              ) : (
                <>
                  <Sparkles size={16} />
                  Synthesize Mind Map
                </>
              )}
            </button>
          </div>
          {aiError && (
            <p className="text-xs text-rose-600 mt-2 font-medium">⚠️ {aiError}</p>
          )}
        </form>
      </div>

      {/* Filters & Topic Selector Bar */}
      <div className="space-y-3">
        {/* Subject Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 text-xs">
          <span className="text-slate-400 font-semibold px-1 shrink-0 flex items-center gap-1">
            <Filter size={13} /> Subject:
          </span>
          {subjectsList.map((subj) => (
            <button
              key={subj}
              onClick={() => setSelectedSubject(subj)}
              className={`px-3 py-1 rounded-full font-medium transition-all whitespace-nowrap ${
                selectedSubject === subj
                  ? "bg-slate-900 text-white shadow-xs"
                  : "bg-white text-slate-600 hover:bg-slate-100 border border-slate-200"
              }`}
            >
              {subj}
            </button>
          ))}
        </div>

        {/* Exam Focus Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 text-xs">
          <span className="text-slate-400 font-semibold px-1 shrink-0">🎯 Exam Focus:</span>
          {["All", "UPSC Prelims", "UPSC Mains", "UPPSC Prelims", "UPPSC Mains"].map((filter) => (
            <button
              key={filter}
              onClick={() => setSelectedExamFilter(filter)}
              className={`px-2.5 py-0.5 rounded-md font-medium transition-all whitespace-nowrap ${
                selectedExamFilter === filter
                  ? "bg-amber-800 text-amber-50"
                  : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
            >
              {filter}
            </button>
          ))}
        </div>
      </div>

      {/* Main Mind Map Grid (Left: Map Selection & Details; Right: Visualization Canvas) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        
        {/* Left Sidebar: Mind Map Topics List */}
        <div className="lg:col-span-4 bg-white rounded-xl border border-slate-200/80 p-4 shadow-xs space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">
              Compiled Mind Maps ({filteredMindMaps.length})
            </h3>
            <span className="text-[11px] font-semibold text-amber-800 bg-amber-50 px-2 py-0.5 rounded-md border border-amber-200/60">
              {selectedSubject}
            </span>
          </div>

          {/* Quick Search */}
          <div className="relative">
            <Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search concepts or traps..."
              className="w-full pl-8 pr-3 py-1.5 text-xs rounded-md border border-slate-200 focus:outline-none focus:ring-1 focus:ring-amber-500 bg-slate-50/50"
            />
          </div>

          {/* Topic Cards */}
          <div className="space-y-2 max-h-[600px] overflow-y-auto pr-1">
            {filteredMindMaps.map((map) => {
              const isSelected = map.id === selectedMindMapId;
              return (
                <div
                  key={map.id}
                  onClick={() => {
                    setSelectedMindMapId(map.id);
                    setActiveNodeDetails(null);
                  }}
                  className={`p-3 rounded-lg border text-left cursor-pointer transition-all duration-150 ${
                    isSelected
                      ? "bg-amber-50/80 border-amber-300 ring-1 ring-amber-400 shadow-xs"
                      : "bg-white border-slate-200 hover:border-amber-200 hover:bg-slate-50"
                  }`}
                >
                  <div className="flex items-center justify-between gap-1 mb-1">
                    <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-slate-100 text-slate-700">
                      {map.subject}
                    </span>
                    <div className="flex items-center gap-1">
                      {map.examFocus.slice(0, 2).map((focus) => (
                        <span
                          key={focus}
                          className="text-[9px] font-semibold px-1 rounded bg-amber-100/70 text-amber-900"
                        >
                          {focus.replace(" Prelims", " Pre").replace(" Mains", " Main")}
                        </span>
                      ))}
                    </div>
                  </div>

                  <h4 className="text-xs font-bold text-slate-900 leading-snug line-clamp-2">
                    {map.title}
                  </h4>
                  <p className="text-[11px] text-slate-500 mt-1 line-clamp-2">
                    {map.description}
                  </p>

                  {/* Flowchart Indicator */}
                  {map.flowchart && (
                    <div className="flex items-center gap-1 mt-2 text-[10px] font-medium text-emerald-700">
                      <Workflow size={11} />
                      <span>{map.flowchart.steps.length}-Step Flowchart Included</span>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Canvas: Selected Mind Map Workspace */}
        <div className="lg:col-span-8 space-y-4">
          
          {/* Active Map Header Details */}
          <div className="bg-white rounded-xl border border-slate-200/80 p-5 shadow-xs space-y-3">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="px-2 py-0.5 rounded text-[11px] font-bold bg-amber-100 text-amber-900 border border-amber-200">
                    {activeMap.subject}
                  </span>
                  {activeMap.examFocus.map((f) => (
                    <span
                      key={f}
                      className="px-2 py-0.5 rounded text-[10px] font-semibold bg-slate-100 text-slate-700"
                    >
                      {f}
                    </span>
                  ))}
                </div>
                <h3 className="text-lg sm:text-xl font-bold font-display text-slate-900 mt-1">
                  {activeMap.title}
                </h3>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-2 shrink-0">
                {viewMode === "tree" && (
                  <div className="flex items-center gap-1">
                    <button
                      onClick={expandAll}
                      className="px-2 py-1 text-[11px] font-semibold rounded bg-slate-100 text-slate-700 hover:bg-slate-200 transition-colors"
                    >
                      Expand All
                    </button>
                    <button
                      onClick={collapseAll}
                      className="px-2 py-1 text-[11px] font-semibold rounded bg-slate-100 text-slate-700 hover:bg-slate-200 transition-colors"
                    >
                      Collapse All
                    </button>
                  </div>
                )}

                {onAskAIAboutTopic && (
                  <button
                    onClick={() => onAskAIAboutTopic(activeMap.title)}
                    className="flex items-center gap-1 px-2.5 py-1 text-xs font-semibold rounded-lg bg-amber-800 hover:bg-amber-900 text-amber-50 transition-colors shadow-xs"
                  >
                    <Sparkles size={13} />
                    <span>Ask AI</span>
                  </button>
                )}
              </div>
            </div>

            {/* Sources Citation Pill */}
            <div className="flex items-center gap-2 text-xs text-slate-500 flex-wrap bg-slate-50 p-2 rounded-md border border-slate-100">
              <span className="font-semibold text-slate-700 flex items-center gap-1">
                <BookOpen size={13} /> Compiled Sources:
              </span>
              {activeMap.sources.map((src, i) => (
                <span key={i} className="text-slate-600 bg-white px-2 py-0.5 rounded border border-slate-200 text-[11px]">
                  {src}
                </span>
              ))}
            </div>

            {/* Shortcut Mnemonic Banner */}
            {activeMap.shortcutMnemonic && (
              <div className="p-3 rounded-lg bg-amber-50/70 border border-amber-200 flex items-start justify-between gap-3">
                <div className="flex items-start gap-2">
                  <Lightbulb size={16} className="text-amber-700 mt-0.5 shrink-0" />
                  <div>
                    <span className="text-xs font-bold text-amber-950 uppercase tracking-wider block">
                      Rapid Recall Shortcut / Mnemonic
                    </span>
                    <p className="text-xs text-amber-900 mt-0.5 leading-relaxed font-medium">
                      {activeMap.shortcutMnemonic}
                    </p>
                  </div>
                </div>
                <button
                  onClick={copyMnemonicText}
                  className="p-1.5 rounded-md hover:bg-amber-100 text-amber-800 transition-colors shrink-0"
                  title="Copy Mnemonic"
                >
                  {copiedMnemonic ? <Check size={14} className="text-emerald-700" /> : <Copy size={14} />}
                </button>
              </div>
            )}
          </div>

          {/* VIEW MODE 1: CONCEPT TREE */}
          {viewMode === "tree" && (
            <div className="bg-white rounded-xl border border-slate-200/80 p-5 shadow-xs">
              <div className="flex items-center justify-between pb-3 mb-2 border-b border-slate-100 text-xs text-slate-500">
                <span className="font-semibold text-slate-700">Interactive Concept Nodes</span>
                <div className="flex items-center gap-3 text-[11px]">
                  <span className="flex items-center gap-1">
                    <span className="w-2.5 h-2.5 rounded-full bg-rose-400"></span> Prelims Trap
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="w-2.5 h-2.5 rounded-full bg-violet-400"></span> Mains Keyword
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="w-2.5 h-2.5 rounded-full bg-emerald-400"></span> Exam Fact
                  </span>
                </div>
              </div>

              {/* Tree Container */}
              <div className="py-2 overflow-x-auto">
                {renderTreeNode(activeMap.rootNode)}
              </div>

              {/* Node Inspector Drawer */}
              {activeNodeDetails && (
                <div className="mt-4 p-4 rounded-lg bg-slate-900 text-slate-100 text-xs space-y-2 border border-slate-800 animate-in fade-in duration-200">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-amber-400 uppercase tracking-wider text-[11px]">
                      Node Examination Notes: {activeNodeDetails.label}
                    </span>
                    <button
                      onClick={() => setActiveNodeDetails(null)}
                      className="text-slate-400 hover:text-white text-xs px-1"
                    >
                      ✕ Close
                    </button>
                  </div>
                  <p className="text-slate-300 leading-relaxed font-normal">
                    {activeNodeDetails.notes || "Core conceptual anchor in UPSC syllabus."}
                  </p>
                </div>
              )}
            </div>
          )}

          {/* VIEW MODE 2: SEQUENTIAL FLOWCHART */}
          {viewMode === "flowchart" && (
            <div className="bg-white rounded-xl border border-slate-200/80 p-5 shadow-xs space-y-4">
              <div className="flex items-center justify-between pb-2 border-b border-slate-100">
                <div>
                  <h4 className="text-sm font-bold text-slate-900">
                    {activeMap.flowchart?.title || `${activeMap.title} - Step-by-Step Flowchart`}
                  </h4>
                  <p className="text-xs text-slate-500">
                    Follow the sequential pathway from inception to statutory outcome.
                  </p>
                </div>
                <span className="text-xs font-semibold px-2 py-0.5 rounded bg-emerald-50 text-emerald-800 border border-emerald-200">
                  {activeMap.flowchart?.steps.length || 0} Stages
                </span>
              </div>

              {/* Flowchart Vertical Stages */}
              {activeMap.flowchart ? (
                <div className="relative pl-6 space-y-6 before:absolute before:left-3 before:top-3 before:bottom-3 before:w-0.5 before:bg-amber-300">
                  {activeMap.flowchart.steps.map((step, idx) => (
                    <div key={idx} className="relative">
                      {/* Step Number Circle */}
                      <div
                        className={`absolute -left-6 top-1 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ring-4 ring-white ${
                          step.highlight
                            ? "bg-amber-700 text-amber-100 shadow-xs"
                            : "bg-slate-800 text-slate-100"
                        }`}
                      >
                        {step.step}
                      </div>

                      {/* Card Content */}
                      <div
                        className={`p-4 rounded-lg border transition-all ${
                          step.highlight
                            ? "bg-amber-50/60 border-amber-300 ring-1 ring-amber-200"
                            : "bg-slate-50/60 border-slate-200"
                        }`}
                      >
                        <div className="flex items-center justify-between gap-2 mb-1">
                          <h5 className="text-xs sm:text-sm font-bold text-slate-900">
                            {step.label}
                          </h5>
                          {step.tag && (
                            <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-white border border-slate-200 text-slate-700">
                              {step.tag}
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-slate-600 leading-relaxed">
                          {step.description}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-slate-500 italic py-6 text-center">
                  Flowchart not configured for this topic. Use the AI generator above to build one!
                </p>
              )}
            </div>
          )}

          {/* VIEW MODE 3: SHORTCUT REVISION & MNEMONICS */}
          {viewMode === "shortcuts" && (
            <div className="bg-white rounded-xl border border-slate-200/80 p-5 shadow-xs space-y-4">
              <div className="flex items-center justify-between pb-2 border-b border-slate-100">
                <h4 className="text-sm font-bold text-slate-900 flex items-center gap-1.5">
                  <Lightbulb size={16} className="text-amber-600" />
                  Pre-Exam 3-Minute Revision Snapshot
                </h4>
                <span className="text-[11px] font-semibold px-2 py-0.5 rounded bg-amber-100 text-amber-900">
                  High-Retention Mode
                </span>
              </div>

              {/* Mnemonic Deep Dive */}
              <div className="p-4 rounded-lg bg-linear-to-br from-amber-50 to-orange-50 border border-amber-200 space-y-2">
                <span className="text-[11px] font-bold text-amber-900 uppercase tracking-wide flex items-center gap-1">
                  <Sparkles size={13} /> Formula & Mnemonic Strategy:
                </span>
                <p className="text-sm font-semibold text-slate-900">
                  {activeMap.shortcutMnemonic || "No specific mnemonic recorded."}
                </p>
                <p className="text-xs text-slate-600">
                  Designed to eliminate common statement reversal traps in UPSC Prelims and Assertion-Reason traps in UPPSC Prelims.
                </p>
              </div>

              {/* High Yield Breakdown */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
                <div className="p-3.5 rounded-lg bg-rose-50/50 border border-rose-200 space-y-1.5">
                  <h5 className="text-xs font-bold text-rose-900 flex items-center gap-1">
                    <AlertTriangle size={14} className="text-rose-600" />
                    Prelims Elimination Pitfall
                  </h5>
                  <p className="text-xs text-rose-950 leading-relaxed">
                    Look out for absolute qualifiers ('all', 'only', 'mandatory in all states', 'exclusively'). Also watch for confusion between Art 368 simple majority vs special majority and UP district names (e.g. Nizamabad Azamgarh vs Khurja).
                  </p>
                </div>

                <div className="p-3.5 rounded-lg bg-violet-50/50 border border-violet-200 space-y-1.5">
                  <h5 className="text-xs font-bold text-violet-900 flex items-center gap-1">
                    <FileText size={14} className="text-violet-600" />
                    Mains Answer Value-Addition
                  </h5>
                  <p className="text-xs text-violet-950 leading-relaxed">
                    Always quote relevant Supreme Court judgments (e.g., Kesavananda, Minerva Mills), committee reports (Sarkaria, 2nd ARC), and incorporate a quick flowchart to secure +1.5 marks.
                  </p>
                </div>
              </div>

              {/* Link to Detailed Notes */}
              {activeMap.topicId && onNavigateToNotes && (
                <div className="pt-2 text-right">
                  <button
                    onClick={() => onNavigateToNotes(activeMap.topicId)}
                    className="inline-flex items-center gap-1.5 text-xs font-bold text-amber-800 hover:text-amber-900 underline underline-offset-4"
                  >
                    Read full comprehensive syllabus note
                    <ArrowRight size={13} />
                  </button>
                </div>
              )}
            </div>
          )}

        </div>
      </div>

    </div>
  );
};
